django_crud_app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('notes.urls', namespace="notes")),
)

notes/urls.py
from django.conf.urls import patterns, url

from notes import views

urlpatterns = patterns('', 
	url(r'^$', views.index, name='index'),
	url(r'^(?P<note_id>\d+)/$', views.read, name='read'),
	url(r'^(?P<note_id>\d+)/delete/$', views.delete, name='delete'),
	url(r'^create/$', views.create, name='create'),
	url(r'^update/$', views.update, name='update'),
)

notes/models.py
from django.db import models

class Note(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	first_published_date = models.DateTimeField(auto_now=True)
	last_update_date = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		"""Returns a pretty output when someone calls Note.objects.all()"""
		return self.title

notes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils import timezone
import datetime
import time
from django import forms

from notes.models import Note

class NotesForm(forms.Form):
    title = forms.CharField(max_length=150)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':30, 'cols':65}))
    noteid = forms.CharField()

def index(request):
	"""Lists all of the Notes in the Database"""
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	print list_of_notes
	if len(list_of_notes) == 0:
		template = 'notes/create.html'
		note = Note(title='', content='')
		note.save()
		form = NotesForm()
		list_of_notes = Note.objects.all().order_by('-last_update_date')
		noteid = list_of_notes[0].id
		context = {'list_of_notes': list_of_notes, 'form':form, 'noteid': noteid}
		return render(request, template, context)
	else:
		target = list_of_notes[0]
		noteid = list_of_notes[0].id
		template = 'notes/base.html'
		if target.title == '':
			target.title = 'Write title here'
		if target.content == '':
			target.content = 'Write content here'
		form = NotesForm(initial={'title': target.title, 'content': target.content})
		context = {'list_of_notes': list_of_notes, 'target': target, 'form':form, 'noteid': noteid}
		return render(request, template, context)

def create(request):
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	template = 'notes/create.html'
	if len(list_of_notes) == 0:
		note = Note(title='', content='')
		note.save()
	elif not list_of_notes[0].title == '':
		note = Note(title='', content='')
		note.save()
	form = NotesForm()
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	noteid = list_of_notes[0].id
	context = {'list_of_notes': list_of_notes, 'form':form, 'noteid': noteid}
	return render(request, template, context)


def read(request, note_id):
	"""Reads a specific note from the Database"""
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	template = 'notes/base.html'
	note = Note.objects.get(id=note_id)
	noteid = note.id
	target = Note.objects.get(id=note_id)
	if target.title == '':
		target.title = 'Write title here'
	if target.content == '':
		target.content = 'Write content here'
	form = NotesForm(initial={'title': target.title, 'content': target.content})
	context = {'list_of_notes': list_of_notes, 'target': target, 'form': form, 'noteid': noteid}
	return render(request, template, context)

def update(request):
	"""Updates a specific note in the Database"""
	template = 'notes/update.html'
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	if request.method == 'POST':
		form = NotesForm(request.POST)
		if form.is_valid():
			title = form.cleaned_data['title']
			content = form.cleaned_data['content']
			noteid = form.cleaned_data['noteid']
			note = Note.objects.get(pk=noteid)
			note.title = title
			note.content = content
			note.save()
			return HttpResponseRedirect('/')
	else:
		form = NotesForm()
		context = {'list_of_notes': list_of_notes, 'form':form}
		return render(request, template, context)	

def delete(request, note_id):
	"""Deletes a specific note from the Database"""
	list_of_notes = Note.objects.all().order_by('-last_update_date')
	template = 'notes/base.html'
	target = Note.objects.get(id=note_id)
	tempid = target.id
	target.delete()
	deleted = True
	context = {'deleted': deleted, 'tempid': tempid, 'list_of_notes': list_of_notes}
	return render(request, template, context)

django_crud_app/notes/templates/notes/index.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
</head>

<body>
	{% if list_of_notes %}
		<h1>List of notes:</h1>
		{% for note in list_of_notes %}
		<p>{{ note.title }}</p>
		{% endfor %}
	{% else %}
		<h1>No data returned</h1>
	{% endif %}
</body>
</html>

notes/templates/notes/backup.html
{% block empty %}
    {% if list_of_notes %}
        <h1>List of notes:</h1>
        {% for note in list_of_notes %}
        <p>{{ note.title }}</p>
        {% endfor %}
    {% else %}
        <h3>Error: No data received at index.html. Please refresh page.</h3>
    {% endif %}
{% endblock empty %}


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="main_container">
            <section class="notes_list">
                <a><div class="note_selector">
                    <h2>Fourth Note: Black Strap Molasses is rather tasty</h2>
                    <p>Last edited: 3/20/1980</p>
                </div></a>
                <a><div class="note_selector selected">
                    <h2>Third Note: Stanley Kubrik is a lower form of deity</h2>
                    <p>Last edited: 3/20/1980</p>
                </div></a>
                <a><div class="note_selector">
                    <h2>Second Note: Never eat a sausage. It will do you no good</h2>
                    <p>Last edited: 3/20/1980</p>
                </div></a>
                <a><div class="note_selector">
                    <h2>First Note: A calm yet spacey afternoon cooks in secret</h2>
                    <p>Last edited: 3/20/1980</p>
                </div></a>

                <div class="nav_buttons">
                    <a>+</a>
                    <a>–</a>
                    <a><img src="{% static 'notes/savedisk.png' %}" alt="Save" title="save"></a>
                </div>

            </section> <!-- notes_list -->

            <section class="note_text">
                <h1>Third Note: Stanley Kubrik is a lower form of deity</h1>
                
                <p>Lorem ipsum dolor sit amet, ei dolorum albucius signiferumque vis, pri in audire detraxit efficiantur, dico dicta democritum nam in. Usu id audire officiis evertitur, qui eirmod vocent probatus ut. Sed id quidam periculis neglegentur, ne vix iriure deseruisse, at per appareat ocurreret. No vis summo placerat. Te iusto molestie sea, deseruisse quaerendum est ut. Ad tantas officiis mea.</p>

                <p>Et graeci legendos concludaturque pri. In cum sint causae mnesarchum, quodsi probatus eu sit. No elit conceptam mea, an pro prompta euismod, an libris luptatum eam. Accusam neglegentur et sit, quo ea simul dissentias. Labore assentior ius te, his eu solum nostro, at nec praesent disputando. Utinam postulant suscipiantur vel ex.</p>

                <p>Cu sea ridens oblique imperdiet. Eu duo brute volumus. Ei duo salutatus percipitur. Vidit laudem civibus ei per, appetere corrumpit ex mei, lorem audiam sapientem usu an. Enim civibus ex has, an dolorum tibique constituam per, mea ex clita quando. Ludus blandit ad has, te saperet admodum detraxit mel. Quem euismod signiferumque est ne, solum definitiones per no, ad atomorum appellantur sed.</p>

                <p>Nominavi delectus iudicabit mel id, id eum perfecto erroribus. Sea nominati adipiscing sadipscing cu. Nam sale oblique numquam ut. Ius ut invenire rationibus, primis inciderint no nec. Constituto disputationi est te, nam verterem sententiae definiebas ea, vim tantas audire disputando ut. In eum utinam iudicabit complectitur, ne ponderum luptatum interesset sea.</p>

                <p>Quod diam diceret sea ex, dico summo definitionem in mei. Cu sed sumo latine, no elitr nihil labores nec. Usu ne nonumy prodesset, ex per agam inani suscipit. Vel saepe deseruisse ne. Qui in nihil iuvaret gloriatur, eum libris debitis ut. An oblique facilisis nec, per an putant debitis dissentiet. Id atqui dolor nam, sit ornatus tibique blandit et, eam eu tota tacimates conclusionemque.</p>
            </section>

            <div style="clear:both;"></div>

        </div> <!-- main_container -->





        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <script>
            //Google Analytics Code Here
        </script>
    </body>
</html>


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="main_container">
            {% if not deleted %}
                <form action="/notes/" method="post">{% csrf_token %}
            {% else %}
                <form method="post" action="javascript:;">
            {% endif %}

            <section class="notes_list">
                {% block empty %}
                    {% if list_of_notes %}
                        {% if newspace %}
                            <a href="javascript:;">
                                <div class="note_selector selected">
                                    <h2>New note</h2>
                                    <p>To be published now</p>
                                </div>
                            </a>
                        {% endif %}
                        {% for note in list_of_notes %}
                            <a href="{% url 'notes:read' note_id=note.id %}">
                                <div class="note_selector {% if note.id == target.id %} selected {% endif %}">
                                <h2>{{ note.title }}</h2>
                                <p>Last edited: {{ note.last_update_date }}</p>
                                </div>
                            </a>
                        {% endfor %}
                    {% endif %}
                    
                <div class="nav_buttons">
                    <input type="submit" value="+">
                    <a href="{% if not deleted %}{% url 'notes:delete' note_id=target.id %}{% else %}javascript:;{% endif %}">–</a>
                    <a href="{# url 'notes:update' note_id=target.id #}"><img src="{% static 'notes/savedisk.png' %}" alt="Save" title="save"></a>
                </div>

            </section> <!-- notes_list -->

            <section class="note_text">
                {% if list_of_notes %}
                    {% if newspace %}
                        <a href="javascript:;">
                            <div class="note_selector selected">
                                <h2>New note</h2>
                                <p>To be published now</p>
                            </div>
                        </a>
                    {% else %}
                        {% if deleted %}
                            <h1>Note: {{ tempid }} was deleted</h1>
                            <p>Please enter a note</p>
                        {% else %}
                                <input class="noteTitle" type="text" name="note_title" value="{{ target.title }}">
                                <textarea class="noteText" rows="30" cols="70">{{ target.content }}</textarea>
                            </form>
                        {% endif %}
                    {% endif %}
                {% else %}
                    <h1>Please enter a title</h1>
                    <p>Please enter a note</p>
                {% endif %}
            </section>
                {% endblock empty %}
            <div style="clear:both;"></div>

        </div> <!-- main_container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{% static 'notes/main.js' %}"></script>
    </body>
</html>

notes/templates/notes/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="main_container">
            {% if not deleted %}
                <form action="/update/" method="post">{% csrf_token %}
            {% else %}
                <form method="post" action="javascript:;">
            {% endif %}

            <section class="notes_list">
                {% for note in list_of_notes %}
                    <a href="{% url 'notes:read' note_id=note.id %}">
                        <div class="note_selector {% if note.id == target.id %} selected {% endif %}">
                        <h2>{{ note.title }}</h2>
                        <p>Last edited: {{ note.last_update_date }}</p>
                        </div>
                    </a>
                {% endfor %}
                
                <div class="nav_buttons">
                    <a href="{% url 'notes:create' %}">+</a>
                    <a href="{% if not deleted %}{% url 'notes:delete' note_id=target.id %}{% else %}javascript:;{% endif %}">–</a>
                    <input type="submit" value='' style="background:url({% static 'notes/savedisk.png' %}) no-repeat;">
                </div>

            </section> <!-- notes_list -->

            <section class="note_text">
                {% if deleted %}
                    <h1>Note: {{ tempid }} was deleted</h1>
                    <p>Please enter a note</p>
                {% else %}
                    {{ form.non_field_errors }}
                    <div class="note_title">
                        {{ form.title.errors }}
                        <label for="id_title"></label>
                        {% if form.title %}
                            {{ form.title }}
                        {% else %}
                            <input type="text" name="title" value="Write title here">
                        {% endif %}
                    </div>
                    <div class="note_content">
                        {{ form.content.errors }}
                        <label for="id_content"></label>
                        {% if form.content %}
                            {{ form.content }}
                        {% else %}
                            <textarea name="content" rows="30" cols="65">Write content here</textarea>
                        {% endif %}
                    </div>
                    <div class="note_id">
                        <label for="id_noteid"></label>
                        <input type="hidden" name="noteid" value="{{ noteid }}">
                    </div>
                   </form>
                {% endif %}
            </section>
                
            <div style="clear:both;"></div>

        </div> <!-- main_container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{% static 'notes/main.js' %}"></script>
    </body>
</html>

notes/templates/notes/create.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="main_container">
            {% if not deleted %}
                <form action="/update/" method="post">{% csrf_token %}
            {% else %}
                <form method="post" action="javascript:;">
            {% endif %}

            <section class="notes_list">
                {% for note in list_of_notes %}
                    <a href="{% url 'notes:read' note_id=note.id %}">
                        <div class="note_selector {% if note.id == noteid %} selected {% endif %}">
                        <h2>{{ note.title }}</h2>
                        <p>Last edited: {{ note.last_update_date }}</p>
                        </div>
                    </a>
                {% endfor %}
                    
                <div class="nav_buttons">
                    <a href="{% url 'notes:create' %}">+</a>
                    <a href="{% if not deleted %}{# url 'notes:delete' note_id=target.id #}{% else %}javascript:;{% endif %}">–</a>
                    <input type="submit" value='' style="background:url({% static 'notes/savedisk.png' %}) no-repeat;">
                </div>

            </section> <!-- notes_list -->

            <section class="note_text">
                {% if deleted %}
                    <h1>Note: {{ tempid }} was deleted</h1>
                    <p>Please enter a note</p>
                {% else %}
                    {{ form.non_field_errors }}
                    <div class="note_title">
                        {{ form.title.errors }}
                        <label for="id_title"></label>
                        <input type="text" name="title" value="Write title here">
                    </div>
                    <div class="note_content">
                        {{ form.content.errors }}
                        <label for="id_content"></label>
                        <textarea name="content" rows="30" cols="65">Write content here</textarea>
                    </div>
                    <div class="note_id">
                        <label for="id_noteid"></label>
                        <input type="hidden" name="noteid" value="{{ noteid }}">
                    </div>
                   </form>
                {% endif %}
            </section>
            <div style="clear:both;"></div>

        </div> <!-- main_container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{% static 'notes/main.js' %}"></script>
    </body>
</html>

notes/templates/notes/update.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->



        <div class="main_container">
            {% if not deleted %}
                <form action="/" method="post">{% csrf_token %}
            {% else %}
                <form method="post" action="javascript:;">
            {% endif %}

            <section class="notes_list">
                {% for note in list_of_notes %}
                    <a href="{% url 'notes:read' note_id=note.id %}">
                        <div class="note_selector {% if note.id == target.id %} selected {% endif %}">
                        <h2>{{ note.title }}</h2>
                        <p>Last edited: {{ note.last_update_date }}</p>
                        </div>
                    </a>
                {% endfor %}
                    
                <div class="nav_buttons">
                    <a href="{% url 'notes:create' %}">+</a>
                    <a href="{% if not deleted %}{# url 'notes:delete' note_id=target.id #}{% else %}javascript:;{% endif %}">–</a>
                    <input type="submit" value='' style="background:url({% static 'notes/savedisk.png' %}) no-repeat;">
                </div>

            </section> <!-- notes_list -->

            <section class="note_text">
                {% if deleted %}
                    <h1>Note: {{ tempid }} was deleted</h1>
                    <p>Please enter a note</p>
                {% else %}
                    {{ form.non_field_errors }}
                    <div class="note_title">
                        {{ form.title.errors }}
                        <label for="id_title"></label>
                        {{ form.title }}
                    </div>
                    <div class="note_content">
                        {{ form.content.errors }}
                        <label for="id_content"></label>
                        {{ form.content }}
                    </div>
                    <div class="note_id">
                        <label for="id_noteid"></label>
                        <input type="hidden" name="noteid" value="{{ noteid }}">
                    </div>
                   </form>
                {% endif %}
            </section>
            <div style="clear:both;"></div>

        </div> <!-- main_container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="{% static 'notes/main.js' %}"></script>
    </body>
</html>